### PR TITLE
Reorganize views by service

### PR DESCRIPTION
**Pull request by bcongdon**
Continuation of #75. Moved to organize views by service.

🚨 (Potentially Dangerous) 🚨

Everything appears to have been correctly set with respect to view directories, but it's very possible that I missed something.

### CODE REVIEW

**Comment by sameetandpotatoes** [comment]
I'll clone this later tonight and go through it as thoroughly as I can

**Comment by sameetandpotatoes** [comment]
So this was totally my bad, but anytime in recruiters and quotes (in the controller) where I write `'/../../views/_partials/unapproved_resumes.ejs'`, it should be:
'/../views/_partials/unapproved_resumes.ejs'.

I agree this is probably not the best way to do this (instead probably just get the 200 and then just remove the row from the table), but we should probably make this fix in the meantime

**Comment by bcongdon** [comment]
Alright. Made the fix. 👍

**Comment by sameetandpotatoes** [comment]
👍 Alright I clicked through every page and didn't find anything. I think this is good to merge.

**Pull request merged**
