### PR TITLE
Changes logos to Font Awesome (#87)

### PR DESCRIPTION
**Pull request by redsn0w422**

### CODE REVIEW

**Comment by narendasan** [comment]
@redsn0w422 can you change the font size to be 1.4em-ish. Its a bit too big. there is a class .fa-2x that defines the font size so override that. The medium and fb logos are slightly bigger than twitter and github, can you make the sizes closer. Also can you center the icons in the footer? right now they are at the top of the link boxes

**Comment by redsn0w422** [comment]
@narendasan they look centered to me, and they're currently the same size as the "I" on my machine
image

**Comment by narendasan** [comment]
They should be smaller than the I, see the current site

**Comment by redsn0w422** [comment]
@narendasan fixed

**Pull request merged**
